// <auto-generated />
namespace OnlineHTMLParser.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Intiial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intiial));
        
        string IMigrationMetadata.Id
        {
            get { return "201709280643425_Intiial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
